name: Caesar Cipher CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Install tools
        run: |
          pip install safety ruff bandit

      - name: Lint Ruff
        run: |
          ruff check .

      - name: Lint Bandit
        run: |
          bandit -r . --exclude tests

      - name: Safety (deps vulnerabilities)
        run: |
          safety check
        continue-on-error: true

      - name: Run tests (pytest)
        run: |
          pytest
